pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - or:
        - and:
            - approved-reviews-by >= 2
            - check-success=true
        - and:
            - author=depandabot
            - label=dependencies
    actions:
      merge:
        method: merge
