version: "3.8"

services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_PASSWORD: "password"
        - POSTGRES_USER: "silk" #Make sure this reflects appSettings.json!
      networks:
        - silk_net
      volumes:
        - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
        - ./postgres/data:/var/lib/postgresql/data:delegated

    silk:
      image: velvetthepanda/silk:latest
      depends_on:
        - postgres
      networks:
        - silk_net
      volumes:
        - ./src/Silk.Core/appSettings.json:/Silk/appSettings.json

networks:
    silk_net:
        internal: true