version: "3.8"

services:
    postgres:
      image: postgres:latest
      container_name: pg-docker
      restart: always
      ports:
        5400:5432
      environment:
        POSTGRES_USER: "docker"
        POSTGRES_PASSWORD: "docker"
      volumes:
        - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
        - ./postgres/data:/var/lib/postgresql/data:delegated
      command: postgres -c config_file=/postgres/postgres.conf
    
      silk:
        image: silk:latest
        container_name: silk-docker
        build: .
        volumes:
          - ./src/Silk.Core/appSettings.json:/out/appSettings.json