version: "3.8"

services:
    postgres:
      image: postgres:latest
      volumes:
        - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
        - ./postgres/data:/var/lib/postgresql/data:delegated
      command: postgres -c config_file=/user/local/etc/postgres/postgres.conf 
    silk:
      image: silk:latest
      build: .
      volumes:
        - ./src/Silk.Core/appSettings.json:/Silk/appSettings.json